apiVersion: batch/v1
kind: Job
metadata:
  name: sop-ingest
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sop-ingest
          image: fde-cold-chain:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          command: ["python", "scripts/ingest_sop_pinecone.py"]
